###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   06/10/2020
#   @package        :   Camera
#   @description    :   All the Camera related stuff 
###############################################################################

camera:
  - platform: mjpeg
    name: Garage Door Cam 
    mjpeg_url: !secret garage_cam # foscam
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: ffmpeg
    input: !secret livingroom_cam # wyze cam v2
    name: livingroom camera
  - platform: ffmpeg
    input: !secret kitchen_cam # wyze cam v2
    name: kitchen camera
  - platform: ffmpeg
    input: !secret theater_cam # wyze cam v2
    name: theater camera
  - platform: ffmpeg
    input: !secret laundry_cam # wyze cam v2
    name: laundry camera
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg  

image_processing:
  - platform: doods
    url: http://192.168.7.187:8080
    detector: default
    scan_interval: 10000
    source:
      - entity_id: camera.driveway
    file_out:
      - "/media/images/{{ camera_entity.split('.')[1] }}_latest.jpg"
    labels:
      - name: person
        confidence: 50

  
          