###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   06/10/2020
#   @package        :   Integrations
#   @description    :   All the Integrations 
###############################################################################

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret

# Testing internet speedtest  
speedtestdotnet:

# Life360 used for presence detection
life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

# Ecobee Thermostat
ecobee:
  api_key: !secret ecobee_api

# calendar:
#   - platform: todoist
#     token: !secret todoist_token
#     custom_projects:
#       - name: 'All Projects'
#       - name: 'Due Today'
#         due_date_days: 0
#       - name: 'Due This Week'
#         due_date_days: 7
#       - name: 'Follow up'
#         labels:
#           - Engagement
#         include_projects:
#           - SlackerLabs
#       - name: 'Work Stuff'
#         include_projects:
#           - Work  

gdacs:
  categories:
    - Earthquake
    - Tropical Cyclone
  radius: 500
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE

# TPLink / KASA - Hardcoding the IP Address
tplink:
  discovery: false
  switch:
    - host: 192.168.7.105
    - host: 192.168.7.107
    - host: 192.168.7.116
    - host: 192.168.7.120
    - host: 192.168.7.136
    - host: 192.168.7.137

# WZYE Devices - Using the HACS integration
wyzeapi:
  username: !secret wyze_user
  password: !secret wyze_password

# IFTTT (May be removed - I dont think I am using this.)
ifttt:
  key: !secret IFTTT_API_KEY 

# Using the HACS Daily Snapshot Clean Up Plugin 
clean_up_snapshots_service:
  host: !secret snapshot_url
  token: !secret snapshot_token
  number_of_snapshots_to_keep: 3

# Hardcoding the Wemo switch
wemo:
  discovery: true
  static:
  - 192.168.7.99

# homekit:
#   filter:
#     include_domains:
#       - light
#     include_entities:
#       - switch.master_bath_fan
#       - switch.master_bedroom_bookcase
#       - switch.rail_lights
#       - switch.skylars_christmas_tree
#       - switch.sleep_aid
#       - switch.artemis
#       - switch.croft_fan
#       - switch.croft_light
#       - switch.dazzned50
#       - switch.desk_lamp
#       - switch.driveway_light
#       - switch.fireplace_lights
#       - switch.forest_incense
#       - switch.front_porch_light
#       - switch.garage_fan
#       - switch.incense
#       - switch.kasa2
#       - switch.kitchen_light_strip
#       - switch.rainbow_light
#       - switch.skylar_led_cube
#       - switch.theater_fan
#       - switch.train_table
#       - switch.wled_loftbed_nightlight
#       - switch.wled_tree_nightlight
#       - switch.3dprinters

