- id: family_has_arrived
  alias: Family Has arrived
  trigger:
  - entity_id: sensor.family_status
    from: Away
    platform: state
    to: Home
  - platform: zone
    entity_id: person.jeffrey
    zone: zone.home
    event: enter
  - entity_id: device_tracker.mal
    from: not_home
    platform: state
    to: home
  - platform: zone
    entity_id: person.katherine
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: script.family_is_home
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.friendly_name == "jeffrey"
          }}'
      sequence:
      - service: script.jeff_destination_na
        data: {}
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.jeff_travel_monitor
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.friendly_name =="katherine"
          }}'
      sequence:
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.kat_travel_monitor
    default: []
  - service: script.driveway_on
    data: {}
  mode: single
  initial_state: true
- id: family_has_left
  alias: Family Has Left
  initial_state: true
  trigger:
  - entity_id: sensor.family_status
    from: Home
    platform: state
    to: Away
  - platform: webhook
    webhook_id: away_webhook
  - entity_id: group.family
    from: home
    platform: state
    to: not_home
  mode: single
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: script.family_is_away
- id: upstairs_fan_on
  alias: Upstairs Fan On
  initial_state: true
  trigger:
  - entity_id: binary_sensor.upstairs_occupancy
    from: 'Off'
    platform: state
    to: 'On'
  condition:
  - above: 73
    condition: numeric_state
    entity_id: sensor.upstairs_temperature
  action:
  - data:
      entity_id: switch.upstairs_fan
    service: switch.turn_on
- id: '1562066108032'
  alias: Living Room Fan On
  initial_state: true
  trigger:
  - entity_id: binary_sensor.living_room_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.livingroom_fan
    state: 'off'
  - above: 73
    condition: numeric_state
    entity_id: sensor.living_room_temperature
  action:
  - data:
      entity_id: switch.livingroom_fan
    service: switch.turn_on
- id: '1562067639239'
  alias: Upstairs Fan Off
  initial_state: true
  trigger:
  - entity_id: binary_sensor.upstairs_occupancy
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.croft_fan
    state: 'on'
  - below: 72
    condition: numeric_state
    entity_id: sensor.upstairs_temperature
  action:
  - data:
      entity_id: switch.croft_fan
    service: switch.turn_off
- id: turn_off_kitchen_speaker
  alias: Turn Off Kitchen Display
  trigger:
  - platform: state
    entity_id: media_player.googlehomehub3492
    from: playing
    to: idle
  action:
  - service: media_player.turn_off
    entity_id: media_player.googlehomehub3492
  initial_state: true
- id: driveway_motion_lighting
  alias: Driveway Motion Lighting
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.aarlo_motion_driveway
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: switch.turn_on
    entity_id: switch.driveway_light
  - delay:
      minutes: 3
  - service: switch.turn_off
    entity_id: switch.driveway_light
- id: show_time_over
  alias: Show Time over
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.theater_tv
    to: 'off'
    for:
      minutes: 20
  action:
  - service: scene.turn_on
    entity_id: scene.theater_dark
- id: theater_fan_on
  alias: Theater Fan On
  initial_state: true
  trigger:
  - above: 74
    platform: numeric_state
    entity_id: sensor.theater_temperature
  condition:
  - condition: state
    entity_id: media_player.theater_tv
    state: 'on'
  action:
  - data:
      entity_id: switch.theater_fan
    service: switch.turn_on
- id: theater_fan_off
  alias: Theater Fan Off
  initial_state: true
  trigger:
  - below: 72
    platform: numeric_state
    entity_id: sensor.theater_temperature
  condition:
  - condition: state
    entity_id: media_player.theater_tv
    state: 'off'
  action:
  - data:
      entity_id: switch.theater_fan
    service: switch.turn_on
- id: theater_light_pressed_up
  alias: Theater Light Pressed Up
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.theater_light_up
  action:
  - service: scene.turn_on
    entity_id: scene.theater_bright
- id: theater_light_pressed_down
  alias: Theater Light Pressed Down
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.theater_light_down
  action:
  - service: scene.turn_on
    entity_id: scene.theater_dark


- id: '1607350354349'
  alias: WFH Video Call Lights On
  description: ''
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.latlmacr0f9jg5m_c922_pro_stream_webcam_camera
      - binary_sensor.latlmacr0f9jg5m_c922_pro_stream_webcam_2
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: scene.turn_on
    data: {}
    entity_id: scene.jeff_desk_on
  - service: switch.turn_on
    data: {}
    entity_id: switch.tplink_a2
  mode: single
- id: '1607350405537'
  alias: WFH Video Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.latlmacr0f9jg5m_c922_pro_stream_webcam_camera
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.tplink_a2
  mode: single

- id: 'test_tag_event'
  alias: Tag desk is scanned
  description: ''
  trigger:
    platform: event
    event_type: tag_scanned
    event_data:
      tag_id: 27cb75e7-ea9f-4395-a747-28eb1118a890
      device_id: 3B33820C-9851-40CD-931E-32801D4BAE3D
  condition: []
  action:
  - service: notify.jeff_ios
    data:
      message: "Jeff someone scanned desk tag"
  mode: single
