

#################################################################################
### Groups ###

Family:
  - person.jeffrey
  - person.katherine

arriving:
  name: Arriving
  entities: []


House Conditions:
  - climate.first_floor
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

occupancy:
  - binary_sensor.living_room_motion_occupancy
  - binary_sensor.kitchen_motion_occupancy
  - binary_sensor.skylar_bedroom_motion_occupancy
  - binary_sensor.master_bedroom_motion_occupancy
  - binary_sensor.back_door_motion

audio_devices:
  - media_player.kitchen_display
  - media_player.upstairs_speaker
  - media_player.master_bedroom_speaker

Outside Lights:
  - switch.driveway_light
  - switch.front_porch_light
  - light.side_door_light_level
  
External Doors:
  - binary_sensor.side_door
  - binary_sensor.front_door
  - binary_sensor.back_door
  - binary_sensor.laundry_door
  - binary_sensor.garage_door

Garage Doors:
  - binary_sensor.side_door
  - binary_sensor.garage_door

Internal Doors:
  - binary_sensor.attic_door

rgb lr:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp

livingroom tower:
  - light.living_room_tower_lamp

livingroom lamps:
  - light.living_room_lamp
  - light.front_door_lamp

incense:
  - switch.forest_incense_incense
  - switch.artemis
  - switch.incense

all fans:
  - switch.croft_fan
  - switch.livingroom_fan

Skylars Bedroom:
  - light.skylars_dresser_lamp
  - switch.rainbow_lamp # rainbow light
  - light.wled_loftbed
  - switch.skylars_desk

Master Bedroom:
  - light.jeff_lamp
  - light.master_bedroom_dresser_lamp
  - light.kat_lamp
  - light.master_bedroom_tower_lamp
  - light.desk_accent
  - switch.tplink_a2

kitchen:
  - light.kitchen_cabinets
  - switch.kitchen_light_strip

livingroom:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp
  - switch.fireplace_lights
  - switch.rail_lights

theater lights:
  - light.theater_lights

Chores:
  - input_boolean.clean_litterbox
  - input_boolean.heartworm
  - input_boolean.nextguard
  - input_boolean.clean_washer
  - input_boolean.clean_dishwasher
  - input_boolean.clean_towel_day
  - input_boolean.clean_sheet_day
  - input_boolean.clean_kitchen
  - input_boolean.clean_livingroom
  - input_boolean.clean_bathrooms
  - input_boolean.mow_yard
  - input_boolean.replace_hvac_filter