- name: studio normal
  entities:
    light.master_bedroom_dresser_lamp:
      state: 'on'
      brightness: 255
    light.kat_lamp:
      state: 'on'
      brightness: 255
    switch.dazzned50:
      state: 'on'
    switch.tplink_a2:
      state: 'on'
    switch.kasa2:
      state: 'on'
    switch.desk_lamp:
      state: 'on'
    light.desk_lighting:
      state: 'on'
      brightness: 255
    

- name: studio work
  entities:
    light.master_bedroom_dresser_lamp:
      state: 'on'
      brightness: 255
    light.kat_lamp:
      state: 'on'
      brightness: 255
    switch.dazzned50:
      state: 'on'
    switch.tplink_a2:
      state: 'off'
    switch.kasa2:
      state: 'on'
    switch.desk_lamp:
      state: 'on'
    light.desk_lighting:
      state: 'on'
      brightness: 255
    light.desk_accent:
      state: 'on'
      brightness: 76.5

- name: all lights on
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 100
    light.kitchen_cabinet_lights:
      state: 'on'
    switch.upstairs:
      state: 'on'
    group.rgb_lr:
      state: 'on'
      brightness_pct: 100
      rgb_color:
      - 255
      - 255
      - 255
    switch.fireplace_lights:
      state: 'on'
    switch.rail_lights:
      state: 'on'
  id: 18855f121a1d411b832f8eb320a342d6
- name: normal livingroom lighting
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      color_temp: 369
      rgb_color:
      - 255
      - 255
      - 255
  id: 8ae2129ba4484194ae25880851a10e70
- name: dimished livingroom lighting
  entities:
    light.living_room_tower_lamp_level_light_color_on_off:
      state: 'on'
      brightness: 40
      color_temp: 369
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
  id: f04e51bf6fd34d28964735238c132796
- name: illuminations livingroom lighting two
  entities:
    light.tower_lamp_2:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.front_door_lamp:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.living_room_lamp:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
  id: d7d01cb26e1f488cae4fa471adf670a8
- name: illuminations livingroom lighting three
  entities:
    light.tower_lamp_2:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.front_door_lamp:
      state: 'on'
      brightness: 40
    light.living_room_lamp:
      state: 'on'
      brightness: 40
      color_temp: 369
    switch.fireplace_lights:
      state: 'off'
  id: 44d4480a14c4442b9409dda5d51be101
- name: night time livingroom lighting
  entities:
    group.livingroom_tower:
      state: 'on'
      brightness: 10
      color_temp: 369
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
  id: 85749b94d00549eda5e04699918fcc37
- name: livingroom lighting off
  entities:
    group.livingroom_tower:
      state: 'off'
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
  id: d05c18cf0ddb4002ad0b28cc0c7f98f2
- name: diminished kitchen lights
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 25
    switch.kitchen_light_strip:
      state: 'off'
  id: c0d8602152fb480d9731f8671f388b1b
- name: normal kitchen lighting
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 255
    switch.kitchen_light_strip:
      state: 'on'
    light.kitchen_sink:
      state: 'on'
      color_temp: 369
      brightness: 255
  id: bbabfe8623f64c5d9678b603018fece6
- name: security kitchen lighting
  entities:
    light.kitchen_sink:
      state: 'on'
      rgb_color: 
      - 127
      - 0
      - 255
      brightness: 255
  id: bbabfe86234002ad0b28cc0c7f98f223     
- name: kitchen lighting off
  entities:
    light.kitchen_cabinets:
      state: 'off'
    switch.kitchen_light_strip:
      state: 'off'
    light.kitchen_sink:
      state: 'off'
  id: d2f97475841a4b50b0ba06f22f0374cf
- name: lights out
  entities:
    light.kitchen_cabinets:
      state: 'off'
    switch.kitchen_light_strip:
      state: 'off'
    switch.croft_light:
      state: 'off'
    group.rgb_lr:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    group.skylars_bedroom:
      state: 'off'
    group.master_bedroom:
      state: 'off'
    switch.rail_lights:
      state: 'off'
    light.kitchen_sink:
      state: 'off'
  id: e9a130a78603423185af94e892c70cd9
- name: haunted preshow
  entities:
    group.kitchen:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    group.rgb_lr:
      state: 'on'
      brightness: 255
    switch.rail_lights:
      state: 'off'
  id: 98d16bf23ea64d63859f0fa6b8262407
- name: haunted lights out
  entities:
    group.kitchen:
      state: 'off'
    group.livingroom:
      state: 'off'
  id: efe48036612a43a1be2e8ed8862e6db1
- name: wishes preshow
  entities:
    switch.croft_light:
      state: 'off'
    group.rgb_lr:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    switch.rail_lights:
      state: 'on'
    switch.kasa2:
      state: 'off'
  id: 8fe178935ec747c6801fc3f367a10a49
- name: wishes show
  entities:
    switch.kasa2:
      state: 'on'
    light.living_room_lamp:
      state: 'on'
      brightness: 20
    light.front_door_lamp:
      state: 'on'
      brightness: 20
    light.living_room_tower_lamp:
      state: 'on'
      brightness: 20
  id: cf27a902be0f49c6bd1727c0d617065c
- name: table lamp blue
  entities:
    light.living_room_lamp:
      state: 'on'
      brightness_pct: 100
      rgb_color:
      - 65
      - 105
      - 255
  id: b76a807484234e2382443165742f2db6
- name: tower lamp red
  entities:
    light.living_room_tower_lamp:
      state: 'on'
      brightness_pct: 100
      rgb_color:
      - 255
      - 40
      - 0
  id: 8778e240c51743d3add7c59150e40d0e
- name: front lamp green
  entities:
    light.front_door_lamp:
      state: 'on'
      brightness_pct: 100
      rgb_color:
      - 0
      - 128
      - 0
  id: c70ecd369eae4513b69a875ad54a53e0

- name: master bedroom on
  entities:
    light.desk_lamp:
      state: 'on'
    light.kat_lamp:
      state: 'on'
      brightness: 255
      color_temp: 369
    light.master_bedroom_dresser_lamp:
      state: 'on'
      brightness: 255
    light.master_bedroom_tower_lamp:
      state: 'on'
      brightness: 255
      color_temp: 369
    light.desk_lighting:
      state: 'on'
      brightness: 255
  id: d250bb4c5c1644b0a7064a9f36ffec32

- name: master bedroom off
  entities:
    switch.desk_lamp:
      state: 'off'
    light.kat_lamp:
      state: 'off'
    light.master_bedroom_dresser_lamp:
      state: 'off'
    light.master_bedroom_tower_lamp:
      state: 'off'
    light.desk_accent:
      state: 'off'
    switch.kasa2:
      state: 'off'
    light.desk_lighting:
      state: 'off'
      brightness: 255
  id: 06e4b59c35f14054ab7e741445b7fd21

- name: master bedroom dim
  entities:
    light.desk_accent:
      state: 'off'
    light.kat_lamp:
      state: 'off'
    light.jeff_lamp:
      state: 'off'
    light.master_bedroom_tower_lamp:
      state: 'on'
      rgb_color:
        - 255
        - 255
        - 255
      color_temp: 369
      brightness: 102
    light.master_bedroom_dresser_lamp:
      state: 'off'
  id: 85953e56acc94c8b8614347de8aab96a

- name: santa protocol
  entities:
    switch.master_bedroom_bookcase:
      state: 'on'
    switch.rail_lights:
      state: 'on'
  id: 76d0eb7f2e194ecab470de1f38203ce6

- name: skylar room prebed
  entities:
    light.wled_skylarsbed:
      state: 'on'
      brightness: 255
      rgb_color:
      - 63
      - 255
      - 0
    light.skylars_dresser_lamp:
      state: 'on'
      brightness: 255
    light.tower_lamp:
      state: 'off'
    light.tower_spotlight:
      state: 'off'
    switch.skylars_christmas_tree:
      state: 'on'
  id: cc8606f7345f48d59b3c32e900122d75

- name: skylar bedtime
  entities:
    input_boolean.audible_notifications:
      state: 'off'
    light.wled_skylarsbed:
      state: 'on'
      brightness_pct: 100
    switch.rainbow_light:
      state: 'on'
    switch.wled_skylarsbed_nightlight:
      state: 'on'
    light.diffuser_skylars_bedroom:
      state: 'on'
    humidifier.diffuser_skylars_bedroom:
      state: 'on'
    input_boolean.skylar_awake:
      state: 'off'
    input_boolean.skylar_dressed_reminder:
      state: 'off'
    light.skylars_dresser_lamp:
      state: 'off'
    switch.sleep_aid:
      state: 'on'
  id: f4e8d2f594c446ee9f0e41cf46df3a53

- name: skylar awake
  entities:
    switch.rainbow_light:
      state: 'off'

- name: skylar room morning
  entities:
    light.wled_skylarsbed:
      state: 'on'
      brightness_pct: 100
      rgb_color:
      - 63
      - 255
      - 0
    light.diffuser_skylars_bedroom:
      state: 'off'
    light.bedside_lamp:
      state: 'off'
  id: dca10298716d46ad86cb894bfac295a5

- name: skylar room day
  entities:
    light.wled_skylarsbed:
      state: 'off'
  id: b25b0c6dcec049929b2bde5d08f3ce53

- name: skylars night light
  entities:
    light.bedside_lamp:
      state: 'on'
      brightness_pct: 20

- name: film time
  id: film_time
  entities:
    switch.tplink_a2:
      state: 'on'
    light.hair_light:
      state: 'on'
      brightness: 76.5
    switch.dazzned50:
      state: 'on'
    switch.shelly1_500291ed2c47:
      state: 'off'

- name: teams call
  id: teams_call
  entities:
    light.jeff_lamp:
      state: 'on'
      brightness: 67.5
      color_temp: 299
    light.master_bedroom_dresser_lamp:
      state: 'on'
      brightness: 255
    light.kat_lamp:
      state: 'on'
      brightness: 255
    light.master_bedroom_tower_lamp:
      state: 'on'
      brightness: 255
      color_temp: 299
    light.desk_accent:
      state: 'on'
      brightness: 255
      rgb_color:
        - 7 
        - 130
        - 255
    switch.dazzned50:
      state: 'on'
    switch.tplink_a2:
      state: 'off'
    light.warning_light:
      state: 'on'
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 67
    switch.kasa2:
      state: 'on'
    switch.desk_lamp:
      state: 'on'
    light.desk_lighting:
      state: 'on'
      brightness: 255
    
- name: teams call done
  id: teams_call_done
  entities:
    light.warning_light:
      state: 'off'
      

- name: film time over
  id: film_time_over
  entities:
    switch.tplink_a2:
      state: 'off'
    light.studio_accent:
      state: 'off'
    switch.master_bedroom_bookcase:
      state: 'off'
    switch.dazzned50:
      state: 'off'
    light.hair_light:
      state: 'off'
    light.desk_accent:
      state: 'off'
    

- name: lr_cool_white
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      rgb_color:
      - 255
      - 255
      - 255
  id: 0058f17baf6e44bc9dbc537892669a57
- name: lr_blue
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      color_name: blue
  id: fc10ec354fbe4e29acf2caeb8156e41c
- name: lr_red
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      rgb_color:
      - 255
      - 40
      - 0
  id: 8018cda7184d43148370ef32fc474228

- name: theater dark
  entities:
    group.theater_lights:
      state: 'off'
  id: 7e5b57ca735f4fc6b5ca75d4f41b63f0
- name: theater dim
  entities:
    group.theater_lights:
      state: 'on'
      brightness: 40
  id: 59b3ac43a09f43e1bd6ac40950b97d13
- name: theater bright
  entities:
    group.theater_lights:
      state: 'on'
      brightness: 255
  id: 1834362d4b2140b6874d0c6d9c0067e9
- name: all fans off
  entities:
    switch.croft_fan:
      state: 'off'
    switch.livingroom_fan:
      state: 'off'
  id: 6f191916879f4a5290282d675c8d6e39
- name: all fans on
  entities:
    switch.croft_fan:
      state: 'on'
    switch.livingroom_fan:
      state: 'on'
  id: 2f3792fca2f64ba28ed39e7a7b6025f8
- name: holiday inside on
  entities:
    switch.master_bedroom_bookcase:
      state: 'on'
    switch.rail_lights:
      state: 'on'
    light.wled_tree:
      state: 'on'
    
  id: a5e09ec5988a4eab92d0ea527fe72a6a
- name: holiday off
  entities:
    switch.master_bedroom_bookcase:
      state: 'off'
    switch.rail_lights:
      state: 'off'
    light.wled_tree:
      state: 'off'
  id: e4408be905b94d13b918f727362c679b