lockdown_issue:
  name: Issue Preventing Lockdown...Please Check
  done_message: Issue Resolved...Anchorage House Ready to Arm
  entity_id: input_boolean.lockdown_issue
  state: 'on'
  repeat: 2
  can_acknowledge: false
  skip_first: False
  notifiers:
  - all_ios