# - platform: mqtt
#   name: "Garage Motion" # Dome Motion Sensor
#   state_topic: "zwave2mqtt/garage_motion/48/1/0"
#   payload_on: "true"
#   payload_off: "false"
#   device_class: motion

# - platform: mqtt
#   name: "Kitchen Motion" # Kaipule Motion Sensor
#   state_topic: "zwave2mqtt/kitchen_motion/48/1/0"
#   payload_on: "true"
#   payload_off: "false"
#   device_class: motion

# - platform: command_line 
#   name: vlc player
#   command: 'pidof vlc | wc -l'
#   payload_on: 1
#   payload_off: 0
#   scan_interval: 10

- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding